//! The build script's half is reading cargo's environment and doing the
//! I/O; the crate's half is resolving what it read and producing the text.
//! These pin the crate's half: `BuildConfig::from_cargo` over every shape of
//! value cargo can hand over, and the exact text of the directives and the
//! config file.

use hilavitkutin_build::{BuildConfig, Profile, TargetAxis, write_config_file, write_directives};
use notko::Maybe;

fn directives(cfg: &BuildConfig) -> String {
    let mut out = String::new();
    write_directives(cfg, &mut out).expect("writing to a String cannot fail");
    out
}

fn config_file(cfg: &BuildConfig) -> String {
    let mut out = String::new();
    write_config_file(cfg, &mut out).expect("writing to a String cannot fail");
    out
}

#[test]
fn every_cargo_profile_name_resolves_to_its_profile() {
    for (name, expected) in [
        ("dev", Profile::Dev),
        ("dev-opt", Profile::DevOpt),
        ("release", Profile::Release),
        ("profiling", Profile::Profiling),
        ("ci", Profile::Ci),
    ] {
        let cfg = BuildConfig::from_cargo(Maybe::Is(name), Maybe::Isnt);
        assert_eq!(cfg.profile, expected, "profile name {name:?}");
        assert_eq!(
            cfg.pragmas,
            expected.default_pragmas(),
            "pragmas follow {name:?}"
        );
    }
}

#[test]
fn an_absent_or_unknown_profile_falls_back_to_dev() {
    assert_eq!(
        BuildConfig::from_cargo(Maybe::Isnt, Maybe::Isnt).profile,
        Profile::Dev
    );
    assert_eq!(
        BuildConfig::from_cargo(Maybe::Is("bench"), Maybe::Isnt).profile,
        Profile::Dev
    );
    assert_eq!(
        BuildConfig::from_cargo(Maybe::Is(""), Maybe::Isnt).profile,
        Profile::Dev
    );
    assert_eq!(
        BuildConfig::from_cargo(Maybe::Is("Release"), Maybe::Isnt).profile,
        Profile::Dev
    );
}

#[test]
fn an_absent_feature_list_leaves_the_target_unset() {
    assert_eq!(
        BuildConfig::from_cargo(Maybe::Is("release"), Maybe::Isnt).target,
        Maybe::Isnt
    );
}

#[test]
fn the_richest_listed_feature_picks_the_target() {
    for (features, expected) in [
        ("avx512f,avx2,sse2", TargetAxis::Avx512),
        ("avx512", TargetAxis::Avx512),
        ("sse2,avx2", TargetAxis::Avx2),
        ("neon,sve", TargetAxis::Sve),
        ("neon", TargetAxis::Neon),
        ("sse2, avx2 ", TargetAxis::Avx2),
        ("sse2,sse4.1", TargetAxis::Iss64),
        ("", TargetAxis::Iss64),
    ] {
        let cfg = BuildConfig::from_cargo(Maybe::Isnt, Maybe::Is(features));
        assert_eq!(cfg.target, Maybe::Is(expected), "feature list {features:?}");
    }
}

#[test]
fn a_feature_is_matched_whole_never_as_a_prefix() {
    for features in ["avx2x", "avx512vl", "neonx,sve2"] {
        let cfg = BuildConfig::from_cargo(Maybe::Isnt, Maybe::Is(features));
        assert_eq!(
            cfg.target,
            Maybe::Is(TargetAxis::Iss64),
            "feature list {features:?}"
        );
    }
}

#[test]
fn fast_math_emits_the_arvo_cfg_and_nothing_else() {
    let release = BuildConfig::from_cargo(Maybe::Is("release"), Maybe::Isnt);
    assert!(release.fast_math());
    assert_eq!(directives(&release), "cargo::rustc-cfg=arvo_fast_math\n");
}

#[test]
fn without_fast_math_no_directive_is_written() {
    for name in ["dev", "dev-opt", "ci"] {
        let cfg = BuildConfig::from_cargo(Maybe::Is(name), Maybe::Isnt);
        assert!(!cfg.fast_math(), "{name:?} has no FastMath");
        assert_eq!(directives(&cfg), "", "{name:?}");
    }
}

#[test]
fn the_config_file_records_profile_and_fast_math() {
    let release = BuildConfig::from_cargo(Maybe::Is("release"), Maybe::Isnt);
    assert_eq!(
        config_file(&release),
        "# generated by hilavitkutin-build (skeleton placeholder)\n\
         # real schema lands with the wrapper-generation round\n\
         profile = Release\n\
         fast_math = true\n",
    );

    let dev = BuildConfig::from_cargo(Maybe::Isnt, Maybe::Isnt);
    assert_eq!(
        config_file(&dev),
        "# generated by hilavitkutin-build (skeleton placeholder)\n\
         # real schema lands with the wrapper-generation round\n\
         profile = Dev\n\
         fast_math = false\n",
    );
}

/// A sink that refuses every write, so an error from the writer has to come
/// back out of both functions rather than being swallowed.
struct Refusing;

impl core::fmt::Write for Refusing {
    fn write_str(&mut self, _: &str) -> core::fmt::Result {
        Err(core::fmt::Error)
    }
}

#[test]
fn a_failing_writer_is_reported_not_swallowed() {
    let release = BuildConfig::from_cargo(Maybe::Is("release"), Maybe::Isnt);
    assert!(write_directives(&release, &mut Refusing).is_err());
    assert!(write_config_file(&release, &mut Refusing).is_err());

    let dev = BuildConfig::from_cargo(Maybe::Is("dev"), Maybe::Isnt);
    assert!(
        write_directives(&dev, &mut Refusing).is_ok(),
        "nothing to write, so nothing to refuse"
    );
}
