//! Build-script entry point.
//!
//! Consumer `build.rs`:
//!
//! ```no_run
//! fn main() {
//!     hilavitkutin_build::bootstrap_from_buildscript();
//! }
//! ```
//!
//! Stub behaviour per src CL §Impl-time decisions item 4:
//! 1. Read `CARGO_CFG_*` / `PROFILE`.
//! 2. Build a `BuildConfig::from_cargo_env()`.
//! 3. If `FastMath` is active, emit `cargo::rustc-cfg=arvo_fast_math`.
//! 4. Write a placeholder `$OUT_DIR/hilavitkutin-config.toml`.
//!
//! Full rustc-wrapper generation + real config-file schema are
//! deferred to follow-up rounds (see `BACKLOG.md.tmpl`).

use crate::config::BuildConfig;

/// Build-script entry point. Runs on the host at build time; uses
/// `std::env` + `std::fs` because a consumer's `build.rs` always
/// links against `std`.
pub fn bootstrap_from_buildscript() {
    let cfg = BuildConfig::from_cargo_env();

    if cfg.fast_math() {
        println!("cargo::rustc-cfg=arvo_fast_math");
    }

    write_placeholder_config(&cfg);
}

fn write_placeholder_config(cfg: &BuildConfig) {
    let out_dir = match std::env::var_os("OUT_DIR") {
        Some(p) => std::path::PathBuf::from(p),
        // No OUT_DIR — either the script is being probed outside
        // cargo or cargo ran us in an unusual configuration. Degrade
        // silently: the wrapper-generation round will formalise the
        // failure modes.
        None => return,
    };

    let path = out_dir.join("hilavitkutin-config.toml");
    let body = format!(
        "# generated by hilavitkutin-build (skeleton placeholder)\n\
         # real schema lands with the wrapper-generation round\n\
         profile = {:?}\n\
         fast_math = {}\n",
        cfg.profile,
        cfg.fast_math(),
    );

    // Ignore write errors: this file is a placeholder consumed by
    // nothing in the skeleton round. A follow-up round promotes this
    // path to load-bearing and surfaces errors properly.
    let _ = std::fs::write(&path, body);
}
