//! What a build script prints and writes, as text.
//!
//! The consumer's `build.rs` owns everything that touches the host: it
//! reads cargo's environment, prints the directives and writes the file.
//! This module turns a [`BuildConfig`] into the text of both, through
//! `core::fmt::Write`, so the crate itself stays `no_std`.
//!
//! ```no_run
//! use std::fmt::Write as _;
//!
//! use hilavitkutin_build::{
//!     BuildConfig,
//!     write_config_file,
//!     write_directives,
//! };
//!
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let profile = std::env::var("PROFILE").ok();
//!     let features = std::env::var("CARGO_CFG_TARGET_FEATURE").ok();
//!     let cfg = BuildConfig::from_cargo(
//!         profile.as_deref().into(),
//!         features.as_deref().into(),
//!     );
//!
//!     let mut directives = String::new();
//!     write_directives(&cfg, &mut directives)?;
//!     print!("{directives}");
//!
//!     let mut body = String::new();
//!     write_config_file(&cfg, &mut body)?;
//!     let out_dir = std::path::PathBuf::from(
//!         std::env::var_os("OUT_DIR").ok_or("no OUT_DIR")?,
//!     );
//!     std::fs::write(out_dir.join("hilavitkutin-config.toml"), body)?;
//!     Ok(())
//! }
//! ```
//!
//! The config file is a placeholder read by nothing yet; its real
//! schema, and the rustc wrapper, are deferred to follow-up rounds
//! (see `BACKLOG.md.tmpl`).

use core::fmt::Write;

use crate::config::BuildConfig;

/// Write the `cargo::` directives the build script prints, one per line.
///
/// Today that is `cargo::rustc-cfg=arvo_fast_math` when the `FastMath`
/// pragma is active, and nothing otherwise.
pub fn write_directives<W: Write>(cfg: &BuildConfig, out: &mut W) -> core::fmt::Result {
    if cfg.fast_math() {
        out.write_str("cargo::rustc-cfg=arvo_fast_math\n")?;
    }
    Ok(())
}

/// Write the body of the generated config file.
///
/// The build script chooses where it goes; `$OUT_DIR/hilavitkutin-config.toml`
/// is the conventional place.
// FIXME: placeholder schema (profile and fast_math only); the wrapper-generation round defines the real one and its reader.
pub fn write_config_file<W: Write>(cfg: &BuildConfig, out: &mut W) -> core::fmt::Result {
    out.write_str(
        "# generated by hilavitkutin-build (skeleton placeholder)\n\
         # real schema lands with the wrapper-generation round\n",
    )?;
    writeln!(out, "profile = {:?}", cfg.profile)?;
    writeln!(out, "fast_math = {}", cfg.fast_math())
}
